### ISSUE TITLE
Make maven part of travis build

### ISSUE THREAD

**Issue by vidstige** [vidstige/jadb#26]
To make sure the Maven build keeps green, it would be great to have the maven build run as part of the travis build. This would catch problems such as the one caused by pull request #22

**Comment by SKART1** [comment]
Will try to deal with this issue soon

**Comment by SKART1** [comment]
First of all need to separate tests for `unit` and ` integration` because  travis do not have android device on board

**Comment by SKART1** [comment]
@vidstige [here](https://github.com/vidstige/jadb/compare/master...SKART1:IMP-26-maven-for-trabis?expand=1) is the cross-repo compare - it solves task of separating unit tests from integration tests

**Comment by vidstige** [comment]
This is already handlet - You can see the log from latest master here: https://travis-ci.org/vidstige/jadb

As you can see travis picked up the pom.xml file and now builds only using maven. In the RealDeviceTest on line 40, there is a line that makes junit ignore all tests in that fixture if the setup cannot be performed.

**Comment by SKART1** [comment]
I think it is not the best practice to mix unit tests and integration test - because:
1. Attaching real device to computer - which can be done accidentally  will result in changing test results
2. Unit tests are extremely quick in comparison to integration tests and may be used for TDD practice - as control that all is ok. If tests are mixed you will not be able see "regression" 

So I Strongly propose to separate them

**Comment by vidstige** [comment]
Yeah, sure. But it's evidently not _needed_ for maven on travis as that's already working. ^^ I'll check cross fork diffs, but go ahead and make the pr. :+1:
