### ISSUE TITLE
Separate unit tests from integration test 2.0

### ISSUE THREAD

**Issue by SKART1** [vidstige/jadb#36]
#26 was not the best decision separating `unit` and `integration` test by hardcoded  package name. 
This breaks Java feature of `package` visibility - which allows tests to use `package` visible methods and fields of application classes in test classes which have same package name

**Comment by vidstige** [comment]
But only public classes/functions are ever tested by design. Which class would you like to test? Please explain a bit more about this "problem".

**Comment by SKART1** [comment]
For example  - see this [cross-repository comparison](https://github.com/vidstige/jadb/compare/master...SKART1:IMP-38-getprop?expand=1) of #38. 

Shortly - I want to implement `getprop` command of android device.

To make this feature testable I separated this functionality in 2 parts:
 * executing shell command 
 * parsing `inputstream` as a result. 

This allows to test most complicated part without overriding `executeShell` method 
Not to put garbage in module interface only actual `getprop` method is public and `parseProp`  is not.
To actually call this method I need package level access which can be achieved only if test have the same package name as `testable` class

**Comment by vidstige** [comment]
I see, I think it would be a much cleaner solution to just mock the public interface. That way you test _behavior_ rather than _implementation_. The latter is less likely to change, and if it _does_ change you want to change the test. Pros:

* Calls the function exactly as a user of the library would.
* You can also assert what the actual command was, e.g. `getprop`
* No need to expose internal (default visible) methods.
* No needs to mix integration and unit tests.

Disadvantage:
* You will need to extend the FakeAdbServer to also handle `executeShell` output. I can probably help out with this.

**Comment by vidstige** [comment]
Plan B - Just make the `getprop()` function public
